steps:
- name: ':ruby: Test'
  command: 'docker-compose build && docker-compose --project-name $BUILDKITE_JOB_ID run app bundle exec rake spec'
  agents:
    queue: single
- wait
- block: ':rocket: Publish to Gem Server'
  prompt: 'Publish this gem to the server using Fixy::VERSION as the version?'
  branches: 'main'
- name: ':ruby: Build & Publish gem'
  command: 'docker-compose build && docker-compose --project-name $BUILDKITE_JOB_ID run -e CLOUDSMITH_API_KEY app sh .buildkite/publish.sh'
  agents:
    queue: gemstash-publish
  branches: 'main'
  plugins:
  - ssh://git@github.com/Gusto/cloudsmith-auth-buildkite-plugin.git#v2.2.0:
      mode: publish
